import {
  Injectable,
  NotFoundException,
  BadRequestException,
  ForbiddenException,
  Logger,
} from '@nestjs/common';
import { PrismaService } from '../../prisma/prisma.service';
import { SecurityService } from '../security/security.service';
import { StorageService } from '../storage/storage.service';
import { ConfigService } from '@nestjs/config';
import { PDFDocument, rgb, StandardFonts } from 'pdf-lib';
import * as qrcode from 'qrcode';
import * as crypto from 'crypto';
import {
  generateCertificateCode,
  normalizeCertificateCode,
  calculateCodeDigest,
  getCodeLastFour,
  CertificateStatus,
  SecurityEventType,
} from '@certificados/shared';

@Injectable()
export class CertificatesService {
  private readonly logger = new Logger(CertificatesService.name);
  private readonly pepper: string;
  private readonly appUrl: string;

  constructor(
    private readonly prisma: PrismaService,
    private readonly securityService: SecurityService,
    private readonly storageService: StorageService,
    private readonly configService: ConfigService,
  ) {
    this.pepper =
      this.configService.get<string>('CERTIFICATE_CODE_PEPPER') ||
      'default_secure_pepper_change_in_production_32bytes!';
    this.appUrl = this.configService.get<string>('APP_URL') || 'http://localhost:3000';
  }

  /**
   * Genera un certificado PDF usando la plantilla del curso (si existe) o el diseño ornamental por defecto.
   */
  private async buildAutoGeneratedPdfCertificate(data: {
    participantName: string;
    courseName: string;
    institutionName: string;
    instructorName: string;
    issuedAt: Date;
    formattedCode: string;
    verificationToken: string;
    templateStoragePath?: string | null;
    templateConfig?: any;
  }): Promise<Buffer> {
    // Si el curso tiene una plantilla PDF cargada, usarla como fondo base
    if (data.templateStoragePath && require('fs').existsSync(data.templateStoragePath)) {
      try {
        const templateBuffer = await require('fs').promises.readFile(data.templateStoragePath);
        const pdfDoc = await PDFDocument.load(templateBuffer);
        const pages = pdfDoc.getPages();
        if (pages.length > 0) {
          const page = pages[0];
          const { width, height } = page.getSize();

          const fontRegular = await pdfDoc.embedFont(StandardFonts.Helvetica);
          const fontBold = await pdfDoc.embedFont(StandardFonts.HelveticaBold);

          // Configuración personalizada del editor
          const cfg = data.templateConfig || {};
          const yPercent = cfg.nameYPercent !== undefined ? Number(cfg.nameYPercent) / 100 : 0.52;
          const fontSize = cfg.nameFontSize !== undefined ? Number(cfg.nameFontSize) : 26;
          
          const hex = (cfg.fontColorHex || '#14213d').replace('#', '');
          const r = parseInt(hex.substring(0, 2), 16) / 255 || 0.08;
          const g = parseInt(hex.substring(2, 4), 16) / 255 || 0.14;
          const b = parseInt(hex.substring(4, 6), 16) / 255 || 0.28;
          const nameColor = rgb(r, g, b);

          // Nombre del Estudiante (Estampar según la posición Y y tamaño configurado)
          const pName = data.participantName.trim();
          const pNameWidth = fontBold.widthOfTextAtSize(pName, fontSize);
          page.drawText(pName, {
            x: (width - pNameWidth) / 2,
            y: height * yPercent,
            size: fontSize,
            font: fontBold,
            color: nameColor,
          });

          // Código Secreto
          page.drawText(`Código: ${data.formattedCode}`, {
            x: width - 210,
            y: 135,
            size: 10,
            font: fontBold,
            color: nameColor,
          });

          // QR de Verificación
          try {
            const verificationUrl = `${this.appUrl}/verificar/${data.verificationToken}`;
            const qrPngBuffer = await qrcode.toBuffer(verificationUrl, { margin: 1, width: 120 });
            const qrImage = await pdfDoc.embedPng(qrPngBuffer);
            page.drawImage(qrImage, {
              x: width - 150,
              y: 30,
              width: 90,
              height: 90,
            });
          } catch (err) {
            this.logger.warn('Error al estampar QR en plantilla personalizada:', err);
          }

          const pdfBytes = await pdfDoc.save();
          return Buffer.from(pdfBytes);
        }
      } catch (err) {
        this.logger.warn('No se pudo procesar la plantilla PDF personalizada, usando diseño estándar:', err);
      }
    }

    // Plantilla estándar por defecto (Vector Gold & Navy)
    const pdfDoc = await PDFDocument.create();
    const page = pdfDoc.addPage([841.89, 595.28]); // A4 Landscape
    const { width, height } = page.getSize();

    const fontRegular = await pdfDoc.embedFont(StandardFonts.Helvetica);
    const fontBold = await pdfDoc.embedFont(StandardFonts.HelveticaBold);

    // Paleta de Colores
    const navyColor = rgb(0.08, 0.14, 0.28);
    const goldColor = rgb(0.82, 0.58, 0.18);
    const darkGray = rgb(0.18, 0.22, 0.28);
    const mutedGray = rgb(0.45, 0.52, 0.60);

    // Marco Ornamental Exterior (Dorado)
    page.drawRectangle({
      x: 20,
      y: 20,
      width: width - 40,
      height: height - 40,
      borderColor: goldColor,
      borderWidth: 3,
    });

    // Marco Ornamental Interior (Azul Marino)
    page.drawRectangle({
      x: 28,
      y: 28,
      width: width - 56,
      height: height - 56,
      borderColor: navyColor,
      borderWidth: 1.5,
    });

    // Detalle de Esquinas (Cuadrantes Dorados)
    const cornerSize = 12;
    page.drawRectangle({ x: 25, y: height - 37, width: cornerSize, height: cornerSize, color: goldColor });
    page.drawRectangle({ x: width - 37, y: height - 37, width: cornerSize, height: cornerSize, color: goldColor });
    page.drawRectangle({ x: 25, y: 25, width: cornerSize, height: cornerSize, color: goldColor });
    page.drawRectangle({ x: width - 37, y: 25, width: cornerSize, height: cornerSize, color: goldColor });

    // Encabezado Institucional
    const instText = (data.institutionName || 'INSTITUTO EDUCACIONAL & COACHING ACADÉMICO').toUpperCase();
    const instWidth = fontBold.widthOfTextAtSize(instText, 14);
    page.drawText(instText, {
      x: (width - instWidth) / 2,
      y: height - 85,
      size: 14,
      font: fontBold,
      color: navyColor,
    });

    // Título Principal
    const certTitle = 'CERTIFICADO DE ACREDITACIÓN';
    const titleWidth = fontBold.widthOfTextAtSize(certTitle, 26);
    page.drawText(certTitle, {
      x: (width - titleWidth) / 2,
      y: height - 125,
      size: 26,
      font: fontBold,
      color: goldColor,
    });

    // Subtítulo
    const subTitle = 'Otorgado con distinción a:';
    const subWidth = fontRegular.widthOfTextAtSize(subTitle, 13);
    page.drawText(subTitle, {
      x: (width - subWidth) / 2,
      y: height - 175,
      size: 13,
      font: fontRegular,
      color: mutedGray,
    });

    // Nombre del Estudiante
    const pName = data.participantName.trim();
    const pNameWidth = fontBold.widthOfTextAtSize(pName, 26);
    page.drawText(pName, {
      x: (width - pNameWidth) / 2,
      y: height - 220,
      size: 26,
      font: fontBold,
      color: navyColor,
    });

    // Línea divisoria bajo el nombre
    page.drawLine({
      start: { x: (width - Math.max(pNameWidth + 40, 300)) / 2, y: height - 235 },
      end: { x: (width + Math.max(pNameWidth + 40, 300)) / 2, y: height - 235 },
      thickness: 1.5,
      color: goldColor,
    });

    // Texto de la Acreditación
    const textDesc = 'Por haber participado y completado satisfactoriamente el curso / clase de:';
    const descWidth = fontRegular.widthOfTextAtSize(textDesc, 12);
    page.drawText(textDesc, {
      x: (width - descWidth) / 2,
      y: height - 275,
      size: 12,
      font: fontRegular,
      color: darkGray,
    });

    // Nombre del Curso / Tutoría
    const cName = `"${data.courseName.trim()}"`;
    const cNameWidth = fontBold.widthOfTextAtSize(cName, 20);
    page.drawText(cName, {
      x: (width - cNameWidth) / 2,
      y: height - 315,
      size: 20,
      font: fontBold,
      color: goldColor,
    });

    // Fecha de Emisión
    const dateFormatted = new Date(data.issuedAt).toLocaleDateString('es-ES', {
      day: 'numeric',
      month: 'long',
      year: 'numeric',
    });
    const dateText = `Emitido el ${dateFormatted}`;
    const dateWidth = fontRegular.widthOfTextAtSize(dateText, 11);
    page.drawText(dateText, {
      x: (width - dateWidth) / 2,
      y: height - 360,
      size: 11,
      font: fontRegular,
      color: mutedGray,
    });

    // Secciones Inferiores: Firma y Código Secreto QR
    // 1. Firma Coach / Instructora (Izquierda)
    const coachName = data.instructorName || 'Dra. Elena Valenzuela';
    page.drawLine({ start: { x: 80, y: 110 }, end: { x: 300, y: 110 }, thickness: 1, color: navyColor });
    page.drawText(coachName, { x: 80, y: 92, size: 12, font: fontBold, color: navyColor });
    page.drawText('Instructora / Coach Educativa', { x: 80, y: 77, size: 10, font: fontRegular, color: mutedGray });

    // 2. Bloque de Código de Verificación (Centro)
    page.drawText('Código Secreto de Descarga:', { x: 340, y: 95, size: 10, font: fontRegular, color: mutedGray });
    page.drawText(data.formattedCode, { x: 340, y: 77, size: 13, font: fontBold, color: navyColor });

    // 3. QR Code de Autenticidad (Derecha)
    try {
      const verificationUrl = `${this.appUrl}/verificar/${data.verificationToken}`;
      const qrPngBuffer = await qrcode.toBuffer(verificationUrl, { margin: 1, width: 140 });
      const qrImage = await pdfDoc.embedPng(qrPngBuffer);
      page.drawImage(qrImage, {
        x: width - 180,
        y: 50,
        width: 105,
        height: 105,
      });
      page.drawText('Escanear para verificar', {
        x: width - 175,
        y: 40,
        size: 8,
        font: fontRegular,
        color: mutedGray,
      });
    } catch (e) {
      this.logger.warn('Error al incrustar QR en PDF generado:', e);
    }

    const pdfBytes = await pdfDoc.save();
    return Buffer.from(pdfBytes);
  }

  /**
   * Emitir un nuevo certificado digital.
   */
  async issueCertificate(
    data: {
      participantName: string;
      participantEmail?: string | null;
      participantDocument?: string | null;
      courseEventId: string;
      issuedAt?: Date;
      expiresAt?: Date | null;
    },
    file?: Express.Multer.File | null,
    adminId?: string,
    ipAddress?: string,
    userAgent?: string,
  ) {
    // 1. Validar que el curso existe
    const course = await this.prisma.courseEvent.findUnique({
      where: { id: data.courseEventId },
    });
    if (!course || !course.isActive) {
      throw new BadRequestException('El curso/evento seleccionado no es válido o está inactivo.');
    }

    // 2. Guardar o encontrar al participante
    let participant = await this.prisma.participant.findFirst({
      where: {
        fullName: { equals: data.participantName.trim(), mode: 'insensitive' },
        ...(data.participantEmail ? { email: data.participantEmail.trim().toLowerCase() } : {}),
      },
    });

    if (!participant) {
      participant = await this.prisma.participant.create({
        data: {
          fullName: data.participantName.trim(),
          email: data.participantEmail ? data.participantEmail.trim().toLowerCase() : null,
          internalDocument: data.participantDocument ? data.participantDocument.trim() : null,
        },
      });
    }

    // 3. Generar identificadores criptográficos únicos
    const { rawCode, formattedCode } = generateCertificateCode();
    const normalizedCode = normalizeCertificateCode(rawCode);
    const codeDigest = calculateCodeDigest(normalizedCode, this.pepper);
    const codeLastFour = getCodeLastFour(normalizedCode);
    const verificationToken = crypto.randomUUID();

    // 4. Si no se proporcionó archivo PDF, generar uno automáticamente con pdf-lib
    let finalFile = file;
    if (!finalFile) {
      const generatedBuffer = await this.buildAutoGeneratedPdfCertificate({
        participantName: participant.fullName,
        courseName: course.name,
        institutionName: course.institution,
        instructorName: course.instructor,
        issuedAt: data.issuedAt ? new Date(data.issuedAt) : new Date(),
        formattedCode,
        verificationToken,
        templateStoragePath: course.templateStoragePath,
        templateConfig: course.templateConfig,
      });

      finalFile = {
        buffer: generatedBuffer,
        size: generatedBuffer.length,
        originalname: `Certificado_${course.name.replace(/[^a-zA-Z0-9]/g, '_')}.pdf`,
        mimetype: 'application/pdf',
      } as Express.Multer.File;
    }

    // 5. Guardar PDF en almacenamiento privado
    const savedFile = await this.storageService.saveCertificatePdf(finalFile);

    const certFile = await this.prisma.certificateFile.create({
      data: {
        originalName: finalFile.originalname,
        storagePath: savedFile.storagePath,
        mimeType: savedFile.mimeType,
        fileSize: savedFile.fileSize,
        sha256Hash: savedFile.sha256Hash,
      },
    });

    // Generar Public ID amigable (e.g. CERT-2026-X891)
    const year = new Date().getFullYear();
    const randomHex = crypto.randomBytes(2).toString('hex').toUpperCase();
    const publicId = `CERT-${year}-${randomHex}`;

    // Opcional: Estampar QR en el PDF si se subió manualmente
    if (file) {
      try {
        const pdfBuffer = await this.storageService.getFileBuffer(savedFile.storagePath);
        const verificationUrl = `${this.appUrl}/verificar/${verificationToken}`;
        const qrPngBuffer = await qrcode.toBuffer(verificationUrl, { margin: 1, width: 150 });

        const pdfDoc = await PDFDocument.load(pdfBuffer);
        const pages = pdfDoc.getPages();
        if (pages.length > 0) {
          const firstPage = pages[0];
          const qrImage = await pdfDoc.embedPng(qrPngBuffer);
          firstPage.drawImage(qrImage, {
            x: firstPage.getWidth() - 120,
            y: 20,
            width: 100,
            height: 100,
          });
          const stampedPdfBytes = await pdfDoc.save();
          await require('fs').promises.writeFile(savedFile.storagePath, Buffer.from(stampedPdfBytes));
        }
      } catch (err) {
        this.logger.warn('No se pudo estampar el QR automáticamente en el PDF:', err);
      }
    }

    // 6. Crear registro en BD
    const certificate = await this.prisma.certificate.create({
      data: {
        publicId,
        participantId: participant.id,
        courseEventId: course.id,
        codeDigest,
        codeLastFour,
        verificationToken,
        status: CertificateStatus.ACTIVE,
        issuedAt: data.issuedAt ? new Date(data.issuedAt) : new Date(),
        expiresAt: data.expiresAt ? new Date(data.expiresAt) : null,
        certificateFileId: certFile.id,
        createdById: adminId,
      },
      include: {
        participant: true,
        courseEvent: true,
      },
    });

    await this.securityService.logAudit({
      adminId,
      action: 'CERTIFICATE_ISSUED',
      resource: 'Certificate',
      resourceId: certificate.id,
      ipAddress,
      userAgent,
      result: 'SUCCESS',
      metadata: { publicId, participantId: participant.id, courseId: course.id },
    });

    // 7. Enviar o simular correo electrónico al alumno si proporcionó email
    let emailSent = false;
    if (participant.email) {
      const searchUrl = `${this.appUrl}/certificados?code=${formattedCode}`;
      const verifyUrl = `${this.appUrl}/verificar/${verificationToken}`;

      this.logger.log(`================ EMAIL DE NOTIFICACIÓN DE CERTIFICADO ================`);
      this.logger.log(`Para: ${participant.email}`);
      this.logger.log(`Asunto: Su Certificado Digital — ${course.name}`);
      this.logger.log(`Estimado/a ${participant.fullName},`);
      this.logger.log(`Su certificado para "${course.name}" ha sido emitido.`);
      this.logger.log(`Código Secreto de Descarga: ${formattedCode}`);
      this.logger.log(`Enlace de Descarga Directa: ${searchUrl}`);
      this.logger.log(`Enlace de Verificación Pública: ${verifyUrl}`);
      this.logger.log(`========================================================================`);
      emailSent = true;
    }

    return {
      certificate: {
        id: certificate.id,
        publicId: certificate.publicId,
        participantName: participant.fullName,
        participantEmail: participant.email,
        courseName: course.name,
        issuedAt: certificate.issuedAt,
        expiresAt: certificate.expiresAt,
        status: certificate.status,
        verificationToken: certificate.verificationToken,
      },
      secretCode: formattedCode,
      emailSent,
    };
  }

  /**
   * Re-enviar notificación por correo de un certificado.
   */
  async sendCertificateEmailById(certificateId: string, customEmail?: string) {
    const cert = await this.prisma.certificate.findUnique({
      where: { id: certificateId },
      include: { participant: true, courseEvent: true },
    });
    if (!cert) throw new NotFoundException('Certificado no encontrado.');

    const targetEmail = customEmail || cert.participant.email;
    if (!targetEmail) {
      throw new BadRequestException('El participante no tiene un correo electrónico registrado.');
    }

    const verifyUrl = `${this.appUrl}/verificar/${cert.verificationToken}`;

    this.logger.log(`================ RE-ENVIANDO CORREO DE CERTIFICADO ================`);
    this.logger.log(`Para: ${targetEmail}`);
    this.logger.log(`Asunto: Certificado Digital — ${cert.courseEvent.name}`);
    this.logger.log(`Estimado/a ${cert.participant.fullName},`);
    this.logger.log(`Código Público: ${cert.publicId}`);
    this.logger.log(`Enlace de Verificación: ${verifyUrl}`);
    this.logger.log(`====================================================================`);

    return {
      success: true,
      message: `Notificación enviada exitosamente a ${targetEmail}.`,
    };
  }

  /**
   * Buscar certificado por código secreto de descarga.
   */
  async searchBySecretCode(inputCode: string, ipAddress: string, userAgent: string) {
    const normalized = normalizeCertificateCode(inputCode);
    if (!normalized || normalized.length < 5) {
      throw new BadRequestException('Código de certificado no válido.');
    }

    const digest = calculateCodeDigest(normalized, this.pepper);

    const cert = await this.prisma.certificate.findUnique({
      where: { codeDigest: digest },
      include: {
        participant: true,
        courseEvent: true,
      },
    });

    if (!cert) {
      await this.securityService.logSecurityEvent({
        eventType: SecurityEventType.SUSPICIOUS_SEARCH,
        description: `Búsqueda de código fallida (no existente): ${inputCode.substring(0, 8)}...`,
        ipAddress,
        userAgent,
      });
      return {
        success: false,
        message: 'No se encontró ningún certificado con el código ingresado. Verifique e intente nuevamente.',
      };
    }

    // Verificar si está expirado dinámicamente
    let currentStatus = cert.status;
    if (currentStatus === CertificateStatus.ACTIVE && cert.expiresAt && cert.expiresAt < new Date()) {
      currentStatus = CertificateStatus.EXPIRED;
    }

    if (currentStatus === CertificateStatus.REVOKED) {
      return {
        success: false,
        status: CertificateStatus.REVOKED,
        message: 'Este certificado ha sido REVOCADO por la institución emisora. No se permite su descarga.',
        certificate: {
          publicId: cert.publicId,
          participantName: cert.participant.fullName,
          courseName: cert.courseEvent.name,
          issuedAt: cert.issuedAt.toISOString(),
          status: CertificateStatus.REVOKED,
          codeLastFour: cert.codeLastFour,
        },
      };
    }

    if (currentStatus === CertificateStatus.EXPIRED) {
      return {
        success: false,
        status: CertificateStatus.EXPIRED,
        message: 'Este certificado ha VENCIDO.',
        certificate: {
          publicId: cert.publicId,
          participantName: cert.participant.fullName,
          courseName: cert.courseEvent.name,
          issuedAt: cert.issuedAt.toISOString(),
          status: CertificateStatus.EXPIRED,
          codeLastFour: cert.codeLastFour,
        },
      };
    }

    // Generar Download Ticket temporal (2 minutos TTL, 1 solo uso)
    const ticketToken = crypto.randomUUID();
    const expiresAt = new Date(Date.now() + 2 * 60 * 1000); // 2 minutos

    await this.prisma.downloadTicket.create({
      data: {
        ticketToken,
        certificateId: cert.id,
        expiresAt,
        ipAddress,
      },
    });

    return {
      success: true,
      status: currentStatus,
      certificate: {
        publicId: cert.publicId,
        participantName: cert.participant.fullName,
        courseName: cert.courseEvent.name,
        issuedAt: cert.issuedAt.toISOString(),
        expiresAt: cert.expiresAt ? cert.expiresAt.toISOString() : null,
        status: currentStatus,
        codeLastFour: cert.codeLastFour,
      },
      downloadTicket: ticketToken,
    };
  }

  /**
   * Buscar y generar ticket de descarga para un certificado dada una clase y correo/documento del alumno.
   */
  async lookupCertificateByCourseAndStudent(
    courseEventId: string,
    studentEmailOrDocument: string,
    ipAddress: string,
  ) {
    const term = studentEmailOrDocument.trim().toLowerCase();
    if (!term || term.length < 2) {
      throw new BadRequestException('Ingrese un correo o número de documento válido.');
    }

    const cert = await this.prisma.certificate.findFirst({
      where: {
        courseEventId,
        archivedAt: null,
        OR: [
          { publicId: { equals: term, mode: 'insensitive' } },
          { codeLastFour: { equals: term, mode: 'insensitive' } },
          { participant: { email: { equals: term, mode: 'insensitive' } } },
          { participant: { internalDocument: { equals: term, mode: 'insensitive' } } },
          { participant: { fullName: { contains: term, mode: 'insensitive' } } },
        ],
      },
      include: {
        participant: true,
        courseEvent: true,
      },
    });

    if (!cert) {
      return {
        success: false,
        message: 'No se encontró un certificado registrado a su nombre para este curso o clase.',
      };
    }

    if (cert.status === CertificateStatus.REVOKED) {
      return {
        success: false,
        message: 'Este certificado ha sido revocado por la institución emisora.',
      };
    }

    if (cert.status === CertificateStatus.EXPIRED || (cert.expiresAt && cert.expiresAt < new Date())) {
      return {
        success: false,
        message: 'Este certificado ha vencido.',
      };
    }

    // Generar Download Ticket temporal (2 minutos TTL, 1 solo uso)
    const ticketToken = crypto.randomUUID();
    const expiresAt = new Date(Date.now() + 2 * 60 * 1000);

    await this.prisma.downloadTicket.create({
      data: {
        ticketToken,
        certificateId: cert.id,
        expiresAt,
        ipAddress,
      },
    });

    return {
      success: true,
      certificate: {
        publicId: cert.publicId,
        participantName: cert.participant.fullName,
        courseName: cert.courseEvent.name,
        issuedAt: cert.issuedAt.toISOString(),
      },
      downloadTicket: ticketToken,
    };
  }

  /**
   * Descargar el PDF mediante un Download Ticket temporal de un solo uso.
   */
  async getPdfByDownloadTicket(ticketToken: string, ipAddress: string) {
    const ticket = await this.prisma.downloadTicket.findUnique({
      where: { ticketToken },
      include: {
        certificate: {
          include: { certificateFile: true },
        },
      },
    });

    if (!ticket) {
      throw new NotFoundException('Ticket de descarga inválido o inexistente.');
    }

    if (ticket.usedAt !== null) {
      throw new ForbiddenException('Este ticket de descarga ya ha sido utilizado.');
    }

    if (ticket.expiresAt < new Date()) {
      throw new ForbiddenException('El ticket de descarga ha expirado. Por favor busque nuevamente.');
    }

    // Marcar el ticket como consumido de inmediato
    await this.prisma.downloadTicket.update({
      where: { id: ticket.id },
      data: { usedAt: new Date() },
    });

    const cert = ticket.certificate;
    if (cert.status === CertificateStatus.REVOKED) {
      throw new ForbiddenException('El certificado está revocando.');
    }

    const fileBuffer = await this.storageService.getFileBuffer(
      cert.certificateFile.storagePath,
    );

    return {
      buffer: fileBuffer,
      filename: `Certificado-${cert.publicId}.pdf`,
      mimeType: 'application/pdf',
    };
  }

  /**
   * Regenerar y rotar el código secreto de un certificado.
   */
  async rotateSecretCode(certificateId: string, adminId: string, ipAddress: string, userAgent: string) {
    const cert = await this.prisma.certificate.findUnique({ where: { id: certificateId } });
    if (!cert) throw new NotFoundException('Certificado no encontrado.');

    const { rawCode, formattedCode } = generateCertificateCode();
    const normalizedCode = normalizeCertificateCode(rawCode);
    const codeDigest = calculateCodeDigest(normalizedCode, this.pepper);
    const codeLastFour = getCodeLastFour(normalizedCode);

    await this.prisma.certificate.update({
      where: { id: certificateId },
      data: { codeDigest, codeLastFour },
    });

    await this.securityService.logAudit({
      adminId,
      action: 'CERTIFICATE_CODE_ROTATED',
      resource: 'Certificate',
      resourceId: certificateId,
      ipAddress,
      userAgent,
      result: 'SUCCESS',
    });

    return {
      success: true,
      message: 'Código secreto rotado con éxito.',
      newSecretCode: formattedCode,
    };
  }

  /**
   * Revocar un certificado.
   */
  async revokeCertificate(
    certificateId: string,
    reason: string,
    adminId: string,
    ipAddress: string,
    userAgent: string,
  ) {
    const cert = await this.prisma.certificate.findUnique({ where: { id: certificateId } });
    if (!cert) throw new NotFoundException('Certificado no encontrado.');

    await this.prisma.certificate.update({
      where: { id: certificateId },
      data: {
        status: CertificateStatus.REVOKED,
        revokedAt: new Date(),
        revokedById: adminId,
        revocationReason: reason.trim(),
      },
    });

    await this.securityService.logAudit({
      adminId,
      action: 'CERTIFICATE_REVOKED',
      resource: 'Certificate',
      resourceId: certificateId,
      ipAddress,
      userAgent,
      result: 'SUCCESS',
      metadata: { reason },
    });

    return { success: true, message: 'Certificado revocado correctamente.' };
  }

  /**
   * Reactivar un certificado.
   */
  async reactivateCertificate(certificateId: string, adminId: string, ipAddress: string, userAgent: string) {
    const cert = await this.prisma.certificate.findUnique({ where: { id: certificateId } });
    if (!cert) throw new NotFoundException('Certificado no encontrado.');

    await this.prisma.certificate.update({
      where: { id: certificateId },
      data: {
        status: CertificateStatus.ACTIVE,
        revokedAt: null,
        revokedById: null,
        revocationReason: null,
      },
    });

    await this.securityService.logAudit({
      adminId,
      action: 'CERTIFICATE_REACTIVATED',
      resource: 'Certificate',
      resourceId: certificateId,
      ipAddress,
      userAgent,
      result: 'SUCCESS',
    });

    return { success: true, message: 'Certificado reactivado con éxito.' };
  }

  /**
   * Obtener listado administrativo de certificados con paginación y filtros.
   */
  async listCertificates(
    page = 1,
    limit = 20,
    search?: string,
    courseEventId?: string,
    status?: CertificateStatus,
  ) {
    const skip = (page - 1) * limit;
    const where: any = { archivedAt: null };

    if (courseEventId) where.courseEventId = courseEventId;
    if (status) where.status = status;
    if (search) {
      where.OR = [
        { publicId: { contains: search, mode: 'insensitive' } },
        { participant: { fullName: { contains: search, mode: 'insensitive' } } },
        { codeLastFour: { contains: search } },
      ];
    }

    const [items, total] = await Promise.all([
      this.prisma.certificate.findMany({
        where,
        skip,
        take: limit,
        orderBy: { createdAt: 'desc' },
        include: {
          participant: true,
          courseEvent: true,
          createdBy: { select: { fullName: true, email: true } },
          revokedBy: { select: { fullName: true, email: true } },
        },
      }),
      this.prisma.certificate.count({ where }),
    ]);

    return { items, total, page, limit, totalPages: Math.ceil(total / limit) };
  }

  /**
   * Generar código QR (SVG o Data URL) para un certificado.
   */
  async getCertificateQr(certificateId: string) {
    const cert = await this.prisma.certificate.findUnique({ where: { id: certificateId } });
    if (!cert) throw new NotFoundException('Certificado no encontrado.');

    const verificationUrl = `${this.appUrl}/verificar/${cert.verificationToken}`;
    const qrDataUrl = await qrcode.toDataURL(verificationUrl);
    const qrSvg = await qrcode.toString(verificationUrl, { type: 'svg' });

    return {
      verificationUrl,
      qrDataUrl,
      qrSvg,
    };
  }
}
